FROM onlyoffice/documentserver:latest

# Copy our custom rebranded web-apps files directly into the image
COPY web-apps /var/www/onlyoffice/documentserver/web-apps
COPY sdkjs /var/www/onlyoffice/documentserver/sdkjs
